#!/usr/bin/env python


# Primarily sorts the keys of a json file. Makes it easier to diff.

import json

if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('filenames', nargs='+', type=str, help="JSON files to prettify into better JSON.")
    args = ap.parse_args()
    for filename in args.filenames:
        outfile = '.'.join([filename, '2'])
        with open(outfile, 'w') as outf:
            json.dump(json.load(open(filename)), outf, sort_keys=True, indent=True, separators=(',', ': '))
